model:
  name: Kwartz
  description: A chimera model that combines multiple models weighted by their accuracy.
  models:
    - name: ModelA
      weight: 0.5
    - name: ModelB
      weight: 0.3
    - name: ModelC
      weight: 0.2
  evaluation:
    metrics:
      - accuracy
      - precision
      - recall
      - f1_score
  training:
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
  logging:
    level: INFO
    log_file: kwartz_training.log