[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
fix = true
exclude = ["dist", "build", ".venv", "tests", "tools", "src/visuals.py"]

[tool.ruff.lint]
select = ["E","F","I","UP","B","S","C90","SIM","PL","PT"]
ignore = ["S101"]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
exclude = "(dist|build|.venv)/"
ignore_missing_imports = true
files = ["src/schemas.py"]
