[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
fix = true
exclude = ["dist", "build", ".venv", "tests", "tools", "src/visualization/visuals.py"]

[tool.ruff.lint]
select = ["E","F","I","UP","B","S","C90","SIM","PL","PT"]
ignore = ["S101"]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
exclude = "(dist|build|.venv)/"
ignore_missing_imports = true
# Expanded type coverage to entire src/ directory
files = ["src/"]
strict = true
warn_return_any = true
warn_unused_configs = true
show_error_codes = true
warn_redundant_casts = true

[tool.coverage.run]
source = ["src"]
branch = true
omit = [
    "src/tools/*",
    "src/visualization/visuals.py",
    "*/test_*",
    "*/__pycache__/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "except ImportError:",
    "except Exception:"
]
ignore_errors = true
show_missing = true
precision = 2

[tool.coverage.html]
directory = "htmlcov"
